services:
  line-provider:
    build:
      context: ./line_provider
    ports:
      - "8001:8000"

#  score-maker:
#    build:
#      context: ./score_maker
#    ports:
#      - "8002:8000"
#    command: poetry run uvicorn score_maker.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: score_db
    ports:
      - "5432:5432"