services:
  line-provider:
    build:
      context: ./line_provider
    volumes:
      - ./line_provider:/line_provider

  score-maker:
    build:
      context: ./score_maker
    volumes:
      - ./score_maker:/score_maker
    ports:
      - "8002:8000"

  arq-cron:
    build:
      dockerfile: arq_cron.Dockerfile
    volumes:
      - ./arq_cron:/app
    depends_on:
      - redis

  arq-worker:
    build:
      dockerfile: arq_worker.Dockerfile
    volumes:
      - ./arq-worker:/app/arq-worker
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"