services:
  line-provider:
    build:
      context: ./line_provider
    ports:
      - "8001:8000"

  celery-beat:
    build:
      dockerfile: beat.Dockerfile
    depends_on:
      - redis

  celery-worker:
    build:
      dockerfile: worker.Dockerfile
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"