# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: line_provider.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'line_provider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13line_provider.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12,\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x06status\x18\x03 \x01(\x0e\x32\x0b.StatusEnum\"\x12\n\x10GetEventsRequest\"+\n\x11GetEventsResponse\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Event*P\n\nStatusEnum\x12\x15\n\x11STATUS_PROCESSING\x10\x00\x12\x14\n\x10STATUS_LOW_SCORE\x10\x01\x12\x15\n\x11STATUS_HIGH_SCORE\x10\x02\x32\x42\n\x0c\x45ventService\x12\x32\n\tGetEvents\x12\x11.GetEventsRequest\x1a\x12.GetEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'line_provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSENUM']._serialized_start=223
  _globals['_STATUSENUM']._serialized_end=303
  _globals['_EVENT']._serialized_start=56
  _globals['_EVENT']._serialized_end=156
  _globals['_GETEVENTSREQUEST']._serialized_start=158
  _globals['_GETEVENTSREQUEST']._serialized_end=176
  _globals['_GETEVENTSRESPONSE']._serialized_start=178
  _globals['_GETEVENTSRESPONSE']._serialized_end=221
  _globals['_EVENTSERVICE']._serialized_start=305
  _globals['_EVENTSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
